/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mushroomattack;

/**
 *
 * @author S855
 */
public class help extends javax.swing.JFrame {

    /**
     * Creates new form awal
     */
    public help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Best = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();
        caraMain = new javax.swing.JLabel();
        losecon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/kalahJumlah.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jamur < Apel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 18))); // NOI18N
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(230, 180, 170, 140);
        jLabel1.getAccessibleContext().setAccessibleName("LC_kalahJumlah");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/kekurung.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jamur Terkurung", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 18))); // NOI18N
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(60, 180, 170, 140);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apelSemua.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apel Semua", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 18))); // NOI18N
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(140, 320, 170, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/caraEasy.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Level Easy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 18))); // NOI18N
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(640, 180, 170, 140);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/caraHard.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Level hard", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 18))); // NOI18N
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(590, 320, 260, 150);

        Best.setBackground(new java.awt.Color(255, 204, 51));
        Best.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        Best.setForeground(new java.awt.Color(255, 102, 51));
        Best.setText("Back");
        Best.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Best);
        Best.setBounds(410, 480, 184, 53);
        jLayeredPane1.add(gambar);
        gambar.setBounds(1217, 11, 0, 0);

        caraMain.setBackground(new java.awt.Color(204, 204, 255));
        caraMain.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        caraMain.setForeground(new java.awt.Color(51, 51, 255));
        caraMain.setText("Cara Bermain");
        jLayeredPane1.add(caraMain);
        caraMain.setBounds(650, 140, 250, 46);

        losecon.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        losecon.setForeground(new java.awt.Color(255, 51, 51));
        losecon.setText("Loose Condition");
        jLayeredPane1.add(losecon);
        losecon.setBounds(120, 140, 200, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/bg2.jpg"))); // NOI18N
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(-40, 0, 960, 634);
        jLabel2.getAccessibleContext().setAccessibleName("LC_kalahJumlah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestActionPerformed
     new awal().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_BestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new help().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Best;
    private javax.swing.JLabel caraMain;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel losecon;
    // End of variables declaration//GEN-END:variables
}
