/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mushroomattack;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author S855
 */
public class ja extends javax.swing.JFrame {

    int[] status = new int[20];// jumlahnya kemungkinan harus lebih dari jumlha kotak karena arraynya kalo pas ga cukup
    int[] cek1 = new int[9];
    int[] infeksicek1 = new int[9];
    int infeksiakhir;
    int lokasiakhir;
    int hasilcekI;
    int caloninfeksi;
    int lokasi;int nol;
    boolean go = false;
//byte tjamur,tapel;

    /**
     * Creates new form jalan
     */
    public ja() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        jumlahjamur = new javax.swing.JLabel();
        B2 = new javax.swing.JButton();
        gochan = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(977, 659));
        getContentPane().setLayout(null);

        B5.setText("\n");
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5);
        B5.setBounds(410, 230, 120, 80);

        B6.setText("\n");
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B6);
        B6.setBounds(560, 230, 120, 80);

        B7.setText("\n");
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7MouseClicked(evt);
            }
        });
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B7);
        B7.setBounds(260, 330, 120, 80);

        B8.setText(" ");
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B8MouseClicked(evt);
            }
        });
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B8);
        B8.setBounds(410, 330, 120, 80);

        B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png"))); // NOI18N
        B9.setText(" ");
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B9MouseClicked(evt);
            }
        });
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B9);
        B9.setBounds(560, 330, 120, 80);
        jLayeredPane1.add(jumlahjamur);
        jumlahjamur.setBounds(1040, 570, 73, 35);

        B2.setText(" ");
        B2.setMaximumSize(new java.awt.Dimension(83, 51));
        B2.setPreferredSize(new java.awt.Dimension(83, 51));
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B2);
        B2.setBounds(410, 130, 120, 80);

        gochan.setBackground(new java.awt.Color(0, 204, 204));
        gochan.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        gochan.setText("GO");
        gochan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gochanMouseClicked(evt);
            }
        });
        gochan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gochanActionPerformed(evt);
            }
        });
        jLayeredPane1.add(gochan);
        gochan.setBounds(430, 40, 90, 40);

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); // NOI18N
        B1.setText("\n");
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B1);
        B1.setBounds(260, 130, 120, 80);

        B3.setText(" ");
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B3);
        B3.setBounds(560, 130, 120, 80);

        B4.setText("\n");
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B4);
        B4.setBounds(260, 230, 120, 80);
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(1126, 868, 73, 35);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/bg1.jpg"))); // NOI18N
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 950, 650);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 30, 960, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        status[0] = 1;   // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        status[8] = 2;
        // TODO add your handling code here:
    }//GEN-LAST:event_B9ActionPerformed

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked

        JOptionPane.showMessageDialog(rootPane, "Maaf,  ini adalah kotak default mohon klik kotak yang lain");   // TODO add your handling code here:
    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        if (go != true) {
            JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");
        } else {
            if (status[1] == 0) {
                if (status[2] == 1 || status[4] == 1 || status[0] == 1) {

                    status[1] = 1;
                    B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
                    ubahapel(1);
                    jalan();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "anda tidak boleh memilih tempat ini");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");
            }// TODO add your handling code here:
        }
// TODO add your handling code here:
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        if (go != true) {
            JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");
        } else {
            if (status[2] == 0) {
                if (status[1] == 1 || status[5] == 1) {
                    status[2] = 1;
                    B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
                    ubahapel(2);
                    jalan();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "anda tidak boleh memilih tempat ini");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");
            }
        }
//  TODO add your handling code here:
    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
        if (go != true) {
            JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");
        } else {
            if (status[3] == 0) {
                if (status[0] == 1 || status[4] == 1 || status[6] == 1) {
                    status[3] = 1;
                    B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya

                    ubahapel(3);
                    jalan();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        if (go != true) {
            JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");
        } else {
            if (status[4] == 0) {
                if (status[3] == 1 || status[5] == 1 || status[1] == 1 || status[7] == 1) {
                    status[4] = 1;
                    B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
                    ubahapel(4);
                    jalan();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");
            }
        }//       // TODO add your handling code here:
    }//GEN-LAST:event_B5MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        if (go != true) {
            JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");
        } else {
            if (status[5] == 0) {
                if (status[4] == 1 || status[2] == 1 || status[8] == 1) {
                    status[5] = 1;
                    B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
                    ubahapel(5);
                    jalan();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");
            }
        }// 
    }//GEN-LAST:event_B6MouseClicked

    private void B7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseClicked
        if (go != true) {
            JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");
        } else {
            if (status[6] == 0) {
                if (status[3] == 1 || status[7] == 1) {
                    status[6] = 1;
                    B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
                    ubahapel(6);
                    jalan();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Maaf,  ini terisi mohon pilih yang lain");
            }
        }//      // TODO add your handling code here:
    }//GEN-LAST:event_B7MouseClicked

    private void B8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseClicked
        if (go != true) {
            JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");
        } else {
            if (status[7] == 0) {
                if (status[6] == 1 || status[8] == 1 || status[4] == 1) {
                    status[7] = 1;
                    B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
                    ubahapel(7);
                    jalan();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
            }
        }//  TODO add your handling code here:
    }//GEN-LAST:event_B8MouseClicked

    private void B9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MouseClicked

        JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        // TODO add your handling code here:
    }//GEN-LAST:event_B9MouseClicked

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void gochanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gochanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gochanActionPerformed

    private void gochanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gochanMouseClicked

        status[8] = 2;
        status[0] = 1;
        go = true;
// TODO add your handling code here:
    }//GEN-LAST:event_gochanMouseClicked

    void jalan() {

        int lokasi = 0;
        byte j;
        for (j = 0; j < 9; j++) {nol=0;
            if (status[j] == 2) {
                System.out.println("yang jalan sukses -j= " + j);// cek yang merupakan apel
                cekI(j);
                if (infeksicek1[j] >= infeksiakhir) {
                    infeksiakhir = infeksicek1[j];
                    lokasiakhir = cek1[j];
                }
//disimpan di hasilcekI;
            } else {
                System.out.println(" bukan  apel " + j);
            }
           
        }
        switch (lokasiakhir){
                case 1:
        if(status[lokasiakhir+1]==0||status[lokasiakhir-1]==0||status[lokasiakhir+3]==0){
        infeksi(lokasiakhir);
        cekpenuh();} 
        else{ cekskor();}
        break;
               case 2:
        if(status[lokasiakhir-1]==0||status[lokasiakhir+3]==0){
        infeksi(lokasiakhir);
        cekpenuh();} 
        else{ cekskor();}
        break;
                    case 3:
        if(status[lokasiakhir+1]==0||status[lokasiakhir+3]==0||status[lokasiakhir-3]==0){
        infeksi(lokasiakhir);
        cekpenuh();} 
        else{ cekskor();}
        break;
             case 4:
        if(status[lokasiakhir+1]==0||status[lokasiakhir-1]==0||status[lokasiakhir+3]==0||status[lokasiakhir-3]==0){
        infeksi(lokasiakhir);
        cekpenuh();} 
        else{ cekskor();
        }
        break;
         case 5:
        if(status[lokasiakhir-1]==0||status[lokasiakhir+3]==0||status[lokasiakhir-3]==0){
        infeksi(lokasiakhir);
        cekpenuh();} 
        else{ cekskor();}
        break;
              case 6:
        if(status[lokasiakhir+1]==0||status[lokasiakhir-3]==0){
        infeksi(lokasiakhir);
        cekpenuh();} 
        else{ cekskor();}
        break;
                   case 7:
        if(status[lokasiakhir+1]==0||status[lokasiakhir-1]==0||status[lokasiakhir-3]==0){
        infeksi(lokasiakhir);
        cekpenuh();} 
        else{ cekskor();}
        break;
                        case 8:
        if(status[lokasiakhir-1]==0||status[lokasiakhir-3]==0){
        infeksi(lokasiakhir);
        cekpenuh();} 
        else{ cekskor();}
        break;
        }
        
        infeksi(lokasiakhir);
        cekpenuh();
        
    }

    void cekI(byte i) {//kosong enggak?
       
        int bandinginfek = 0;
        lokasi = i - 1;
        if ((i - 1) >= 0 && i != 3 && i != 6) {//cek kiri kosong ga
            int a = i - 1;
            if (status[a] == 0) {
//                System.out.println("cekI bagian1");
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                bandinginfek = caloninfeksi;//dimasukin ke perbandinggan.. yang in tuh isian pertama
                lokasi = a;
                System.out.println("simpan" + a);// terus simpan lokasinya- lokasi ini tuh lokasinya a.. yaitu lokasi   calon anak beda lo sama lokasi infeksi
                //lokasi infeksi ga perlu di inget
            }
        }
        if ((i + 1) <= 8 && i != 2 && i != 5) {//cek kanannya kosong enggak?
            int a = i + 1;
            if (status[a] == 0) {
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                if (caloninfeksi > bandinginfek) {//ayo dilihat dulu sama yang sebelumnya besaran mana?
                    bandinginfek = caloninfeksi;// kalo besar ambil aja yang besar
                    lokasi = a;
                    System.out.println("2" + a);// terus simpan lokasinya
                }
            }
        }
        if ((i + 3) <= 8&& i!=6&& i!=7) {//cek bawahnya kosong ennga?
            int a = i + 3;
            if (status[a] == 0) {
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                if (caloninfeksi > bandinginfek) {//ayo dilihat dulu sama yang sebelumnya besaran mana?
                    bandinginfek = caloninfeksi;// kalo besar ambil aja yang besar
                    lokasi = a;
                    System.out.println("3" + a);// terus simpan lokasinya
                }
            }
        }
        if ((i - 3) >= 0&& i!=1&& i!=2) {//cek atasnya kosog engga?
            int a = i - 3;
            if (status[a] == 0) {
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                if (caloninfeksi > bandinginfek) {//ayo dilihat dulu sama yang sebelumnya besaran mana?
                    bandinginfek = caloninfeksi;// kalo besar ambil aja yang besar
                    lokasi = a;
                    System.out.println("lokasi-");// terus simpan lokasinya
                    System.out.println("lokasi " + a);
                }
            }
        }
        System.out.println("lokasi " + lokasi);
        //oke lokasinya fix terus gimana?jalanin infeksinya dong ><)/"
        cek1[i] = lokasi;
        infeksicek1[i] = bandinginfek;
// infeksi(lokasi);
        System.out.println("print cekI" + lokasi);
    
    }

    void cekII(int i) {// liat sekitarnya kosong ada caloninfeksi engga?
        int k = 0;
        caloninfeksi = 0;// di nolkan dulu biar nanti ga kemasukan lain2
        if ((i + 1) <= 8&& i != 2 && i != 5) {//cek kanannya infeksinya ad?
            k = i + 1;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
        if ((i - 1) >= 0&& i != 3 && i != 6) {//cek kirinya kosong enggak?infeksinya ad?
            k = i - 1;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
        if ((i + 3) <= 8&& i!=6&& i!=7) {//cek bawahnya infeksinya ad?
            k = i + 3;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
        if ((i - 3) >= 0&& i!=1&& i!=2) {//cek atasnya infeksinya ad?
            k = i - 3;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
        System.out.println("nilai calon infeksi =" + caloninfeksi);
    }

    void infeksi(int i) {

        ubahjadiapel(i);
        System.out.println(" ubah apel" + i);
        if ((i + 1) <= 8 && i != 2 && i != 5) {//cek kanannya ada ga? ntar eror lo

            int a = i + 1;
            if (status[a] == 1) {//sasarannnya hidup  ga? 
                ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        if ((i - 1) >= 0 && i != 3 && i != 6) {//cek kirinya kada ga? ntar eror lo
            int a = i - 1;
            if (status[a] == 1) {//ini jamur buat diinfeksi kan?
                ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        if ((i + 3) <= 8) {//cek bawahnya ada ga? ntar eror lo
            int a = i + 3;
            if (status[a] == 1) {//ini jamur buat diinfeksi kan?
                ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        if ((i - 3) >= 0) {//cek atasnya ada ga? ntar eror lo
            int a = i - 3;
            if (status[a] == 1) {//ini jamur buat diinfeksi kan?
                ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        System.out.println("infeksijalan niali a =" + i);
    }
//

    void ubahjadiapel(int a) {
        switch (a) {
            case 0:
                status[0] = 2;
                B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
            case 1:
                status[1] = 2;
                B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 2:
                status[2] = 2;
                B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 3:
                status[3] = 2;
                B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 4:
                status[4] = 2;
                B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 5:
                status[5] = 2;
                B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 6:
                status[6] = 2;
                B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 7:
                status[7] = 2;
                B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 8:
                status[8] = 2;
                B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;

            default:
                System.out.println("eror");

        }

    }
//

    void jadikanjamur(int s) {
        switch (s) {
            case 0:
                status[0] = 1;
                B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
            case 1:
                status[1] = 1;
                B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 2:
                status[2] = 1;
                B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 3:
                status[3] = 1;
                B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 4:
                status[4] = 1;
                B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 5:
                status[5] = 1;
                B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 6:
                status[6] = 1;
                B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 7:
                status[7] = 1;
                B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 8:
                status[8] = 1;
                B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;

            default:
                System.out.println("eror");

        }

    }

    void cekpenuh() {
        int tunggal = 0;
        int tunggallokasi = 0;
        if (status[0] != 0 && status[1] != 0 && status[2] != 0 && status[3] != 0 && status[4] != 0 && status[5] != 0 && status[6] != 0 && status[7] != 0 && status[8] != 0) {
            cekskor();
        }
        for (int i = 0; i < 9; i++) {
            
            
            if (status[i] == 1) {
                tunggal++;
                tunggallokasi = i;
                System.out.println("tunggallokasi= "+tunggal);
            }
        }
       if(tunggal==1){
           cektunggal(tunggallokasi);
       }
       if (tunggal==0){
            JOptionPane.showMessageDialog(rootPane, "Anda kalah");
       }
        
    }
    
    void cektunggal(int i){
        int kosong = 0;
      if ((i + 1) <= 8 && i != 2 && i != 5&& status[i+1]==0) {//cek kanannya ada ga? ntar liat bisa jalan atas bawah atau enggak
kosong ++;
        }
        if ((i - 1) >= 0 && i != 3 && i != 6&& i!=0&& status[i-1]==0) {//cek kirinya kada ga? ntar liat bisa jalan atas bawah atau enggak
          kosong ++;
        }
        if ((i + 3) <= 8&& i != 6 && i != 7 && i!=8&& status[i+3]==0) {//cek bawahnya ada ga? ntar eror lontar liat bisa jalan atas bawah atau enggak
            kosong ++;
        }
        if ((i - 3) >= 0&& i != 0 && i != 1 && i!=2&& status[i-3]==0) {//cek atasnya ada ga? ntar eror lo ntar liat bisa jalan atas bawah atau enggak
          kosong ++;
        }    
    if(kosong==0){
        JOptionPane.showMessageDialog(rootPane, "Anda kalah");
    }
    }
    /**
     *
     */
    void cekskor() {
        int apels = 0;
        int jamurs = 0;
        int pr = 0;
        for (int i = 0; i < 9; i++) {

            if (status[i] == 1) {
                jamurs = jamurs + 10;
                pr++;
            }
            if (status[i] == 2) {
                apels = apels + 10;//cekada(i);
                pr++;
            }

        }
        nilai(jamurs, apels);

    }

    void nilai(int jamurs, int apels) {
        if (jamurs < apels) {
            JOptionPane.showMessageDialog(rootPane, "Anda kalah");
            new nama(jamurs).setVisible(true);
        }
        if (jamurs > apels) {
            JOptionPane.showMessageDialog(rootPane, "Anda menang");
            new nama(jamurs).setVisible(true);
        }
    }
//}

    void cekada(int pare) {
        if (status[pare++] == 2 && status[pare--] == 2 && status[pare + 3] == 2 && status[pare - 3] == 2) {
            JOptionPane.showMessageDialog(rootPane, "Anda kalah");
        }
    }

    void ubahapel(int state) {
        int k;
//mengubah musuh-apel
        if ((state - 3) >= 0) {  //atas
            k = (state - 3);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }
        if ((state + 3) <= 8) {  //bawah
            k = (state + 3);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }
        if ((state - 1) >= 0) {  //kiri
            k = (state - 1);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }
        if ((state + 1) <= 8) {  //kanan
            k = (state + 1);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ja().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton gochan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jumlahjamur;
    // End of variables declaration//GEN-END:variables
}
