/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mushroomattack;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author S855
 */
public class jalanhard extends javax.swing.JFrame {
    //dari easy mode
      int[] status = new int[20];// jumlahnya kemungkinan harus lebih dari jumlha kotak karena arraynya kalo pas ga cukup
    int []cek1=new int[20];
    int []infeksicek1= new int[20];
    int infeksiakhir;
    int lokasiakhir;
    int hasilcekI;
    int caloninfeksi;
    int lokasi;
    boolean go= false;
    
    
    
    
     public jalanhard() {
        initComponents();

    }


   
//    int[] status = new int[20];// jumlahnya kemungkinan harus lebih dari jumlha kotak karena arraynya kalo pas ga cukup
//    
//    int hasilcekI;
//    int caloninfeksi;
//    int lokasi;
//byte tjamur,tapel;

    /**
     * Creates new form jalan
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        B13 = new javax.swing.JButton();
        B14 = new javax.swing.JButton();
        B15 = new javax.swing.JButton();
        B16 = new javax.swing.JButton();
        jumlahjamur = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        B17 = new javax.swing.JButton();
        B18 = new javax.swing.JButton();
        B19 = new javax.swing.JButton();
        B20 = new javax.swing.JButton();
        gochan = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(977, 659));
        getContentPane().setLayout(null);

        B2.setText(" ");
        B2.setMaximumSize(new java.awt.Dimension(83, 51));
        B2.setPreferredSize(new java.awt.Dimension(83, 51));
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B2);
        B2.setBounds(280, 140, 110, 70);

        B3.setText("\n");
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B3);
        B3.setBounds(430, 140, 110, 70);

        B4.setText("\n");
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B4);
        B4.setBounds(580, 140, 110, 70);

        B5.setText("\n");
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B5);
        B5.setBounds(730, 140, 110, 70);

        B6.setText("\n");
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B6);
        B6.setBounds(130, 220, 110, 70);

        B7.setText("\n");
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7MouseClicked(evt);
            }
        });
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B7);
        B7.setBounds(280, 220, 110, 70);

        B8.setText(" ");
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B8MouseClicked(evt);
            }
        });
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B8);
        B8.setBounds(430, 220, 110, 70);

        B9.setText(" ");
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B9MouseClicked(evt);
            }
        });
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B9);
        B9.setBounds(580, 220, 110, 70);

        B10.setText("\n");
        B10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B10MouseClicked(evt);
            }
        });
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B10);
        B10.setBounds(730, 220, 110, 70);

        B11.setText("\n");
        B11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B11MouseClicked(evt);
            }
        });
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B11);
        B11.setBounds(130, 300, 110, 70);

        B12.setText(" ");
        B12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B12MouseClicked(evt);
            }
        });
        B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B12ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B12);
        B12.setBounds(280, 300, 110, 70);

        B13.setText("\n");
        B13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B13MouseClicked(evt);
            }
        });
        B13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B13ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B13);
        B13.setBounds(430, 300, 110, 70);

        B14.setText("\n");
        B14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B14MouseClicked(evt);
            }
        });
        B14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B14ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B14);
        B14.setBounds(580, 300, 110, 70);

        B15.setText("\n");
        B15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B15MouseClicked(evt);
            }
        });
        B15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B15ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B15);
        B15.setBounds(730, 300, 110, 70);

        B16.setText("\n");
        B16.setPreferredSize(new java.awt.Dimension(35, 23));
        B16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B16MouseClicked(evt);
            }
        });
        B16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B16ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B16);
        B16.setBounds(130, 380, 110, 70);
        jLayeredPane2.add(jumlahjamur);
        jumlahjamur.setBounds(780, 580, 73, 35);
        jLayeredPane2.add(jLabel1);
        jLabel1.setBounds(110, 570, 73, 35);

        B17.setText(" ");
        B17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B17MouseClicked(evt);
            }
        });
        B17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B17ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B17);
        B17.setBounds(280, 380, 110, 70);

        B18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B18MouseClicked(evt);
            }
        });
        jLayeredPane2.add(B18);
        B18.setBounds(430, 380, 110, 70);

        B19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B19MouseClicked(evt);
            }
        });
        jLayeredPane2.add(B19);
        B19.setBounds(580, 380, 110, 70);

        B20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png"))); // NOI18N
        B20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B20MouseClicked(evt);
            }
        });
        jLayeredPane2.add(B20);
        B20.setBounds(730, 380, 110, 70);

        gochan.setBackground(new java.awt.Color(255, 0, 102));
        gochan.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        gochan.setText("GO !");
        gochan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gochanMouseClicked(evt);
            }
        });
        gochan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gochanActionPerformed(evt);
            }
        });
        jLayeredPane2.add(gochan);
        gochan.setBounds(440, 60, 90, 40);

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); // NOI18N
        B1.setText("\n");
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(B1);
        B1.setBounds(130, 140, 110, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/bg1.jpg"))); // NOI18N
        jLayeredPane2.add(jLabel3);
        jLabel3.setBounds(0, 0, 960, 630);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(0, 0, 980, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B9ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B10ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B11ActionPerformed

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B12ActionPerformed

    private void B13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B13ActionPerformed

    private void B14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B14ActionPerformed

    private void B15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B15ActionPerformed

    private void B16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B16ActionPerformed

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
       
        JOptionPane.showMessageDialog(rootPane, "Maaf,  ini adalah kotak default mohon klik kotak yang lain");   // TODO add your handling code here:
    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked

      if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[1] == 0) {if(status[0]==1||status [2]==1||status [5]==1||status [6]==1||status [7]==1)
        {
       
                status[1] = 1;
                B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
                ubahapel(1);
                jalan();
        } else{JOptionPane.showMessageDialog(rootPane, "anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");
        }// TODO add your handling code here:
      }
// TODO add your handling code here:
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[2] == 0) {
            if(status[1]==1||status[3]==1||status[6]==1||status[7]==1||status[8]==1){
            status[2] = 1;
            B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
            ubahapel(2);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");
        }}
        //TODO add your handling code here:
    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
   if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");}  else{
        if (status[3] == 0) {
            if(status[2]==1||status[4]==1||status[7]==1||status[8]==1||status[9]==1){
            status[3] = 1;
            B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
            
            ubahapel(3);
            jalan();}else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");
        }
        }       
// TODO add your handling code here:
    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
       if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[4] == 0) {
            if(status[3]==1||status[8]==1||status[9]==1){
            status[4] = 1;
            B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
            ubahapel(4);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");
        }
       }//     // TODO add your handling code here:
    }//GEN-LAST:event_B5MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
         if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[5] == 0) {
            if(status[0]==1||status[1]==1||status[6]==1||status[10]==1||status[11]==1){
            status[5] = 1;
            B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
            ubahapel(5);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");
        }
        }
    }//GEN-LAST:event_B6MouseClicked

    private void B7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseClicked
      if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");}  else{
        if (status[6] == 0) {
            if(status[5]==1||status[7]==1||status[0]==1||status[1]==1||status[2]==1||status[10]==1||status[11]==1||status[12]==1){
            status[6] = 1;
            B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
            ubahapel(6);
            jalan();}else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini terisi mohon pilih yang lain");
        }
        }//    // TODO add your handling code here:
    }//GEN-LAST:event_B7MouseClicked

    private void B8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseClicked
        if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[7] == 0) {
            if(status[6]==1 || status[8]==1||status[1]==1||status[2]==1||status[3]==1||status[11]==1||status[12]==1||status[13]==1){
            status[7] = 1;
            B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(7);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        }//  TODO add your handling code here:
    }//GEN-LAST:event_B8MouseClicked

    private void B9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MouseClicked
        if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[8] == 0) {
            if(status[7]==1 || status[9]==1||status[2]==1||status[3]==1||status[4]==1||status[12]==1||status[13]==1||status[14]==1){
            status[8] = 1;
            B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(8);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        }   // TODO add your handling code here:
    }//GEN-LAST:event_B9MouseClicked

    private void B11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B11MouseClicked
        if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[10] == 0) {
            if(status[5]==1 || status[6]==1||status[15]==1||status[16]==1||status[11]==1){
            status[10] = 1;
            B11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(10);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_B11MouseClicked

    private void B10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B10MouseClicked
          if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[9] == 0) {
            if(status[3]==1 || status[4]==1||status[13]==1||status[14]==1||status[8]==1){
            status[9] = 1;
            B10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(9);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_B10MouseClicked

    private void B13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B13MouseClicked
          if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[12] == 0) {
            if(status[6]==1||status[7]==1||status[8]==1||status[16]==1||status[17]==1||status[18]==1||status[11]==1||status[13]==1){
            status[12] = 1;
            B13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(12);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        }     // TODO add your handling code here:
    }//GEN-LAST:event_B13MouseClicked

    private void B14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B14MouseClicked
          if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[13] == 0) {
            if(status[9]==1||status[7]==1||status[8]==1||status[19]==1||status[17]==1||status[18]==1||status[12]==1||status[14]==1){
            status[13] = 1;
            B14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(13);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        }      // TODO add your handling code here:
    }//GEN-LAST:event_B14MouseClicked

    private void B15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B15MouseClicked
     if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[14] == 0) {
            if(status[8]==1 || status[9]==1||status[18]==1||status[13]==1){
            status[14] = 1;
            B15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(14);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_B15MouseClicked

    private void B12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B12MouseClicked
         if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[11] == 0) {
            if(status[5]==1||status[6]==1||status[7]==1||status[15]==1||status[16]==1||status[17]==1||status[12]==1||status[10]==1){
            status[11] = 1;
            B12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(11);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        }      // TODO add your handling code here:
    }//GEN-LAST:event_B12MouseClicked

    private void B16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B16MouseClicked
      if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[15] == 0) {
            if(status[10]==1||status[11]==1||status[16]==1){
            status[15] = 1;
            B16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(15);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        }   
    }//GEN-LAST:event_B16MouseClicked

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B17MouseClicked
       if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[16] == 0) {
            if(status[10]==1||status[11]==1||status[12]==1||status[15]==1||status[17]==1){
            status[16] = 1;
            B17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(16);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        }     // TODO add your handling code here:
    }//GEN-LAST:event_B17MouseClicked

    private void B17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B17ActionPerformed

    private void B18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B18MouseClicked
        if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[17] == 0) {
            if(status[13]==1||status[11]==1||status[12]==1||status[16]==1||status[18]==1){
            status[17] = 1;
            B18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(17);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_B18MouseClicked

    private void B19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B19MouseClicked
        if(go!= true){ JOptionPane.showMessageDialog(rootPane, "mohon klik GO ! terlebih dahulu");} else{
        if (status[18] == 0) {
            if(status[13]==1||status[14]==1||status[12]==1||status[17]==1||status[19]==1){
            status[18] = 1;
            B19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png"))); //buat imagenya
           ubahapel(18);
            jalan();} else{JOptionPane.showMessageDialog(rootPane, "Anda tidak boleh memilih tempat ini");}
        } else {
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
        }
        } // TODO add your handling code here:
    }//GEN-LAST:event_B19MouseClicked

    private void B20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B20MouseClicked
        
            status[19] = 2;
           
        
            JOptionPane.showMessageDialog(rootPane, "Maaf,  ini sudah terisi mohon pilih yang lain");;
          // TODO add your handling code here:
    }//GEN-LAST:event_B20MouseClicked

    private void gochanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gochanMouseClicked
status [0]=1; status[19]=2;
go=true;
        // TODO add your handling code here:
    }//GEN-LAST:event_gochanMouseClicked

    private void gochanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gochanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gochanActionPerformed

    
    
    
    //dari easy mode
    void jalan() {
        
        int lokasi = 0;byte j;
        for ( j = 0; j <20; j++) {
            if (status[j] == 2) {
 System.out.println("yang jalan sukses -j= "+j);// cek yang merupakan apel
  cekI(j); 
  if(infeksicek1[j]>=infeksiakhir){
      infeksiakhir=infeksicek1[j];
      lokasiakhir= cek1[j];
  }
//disimpan di hasilcekI;
            }
            else {System.out.println(" bukan  apel "+j);}//if( )
        }
      infeksi(lokasiakhir);
      cekpenuh();
    }

    void cekI(byte i) {//kosong enggak?
        int bandinginfek=0;
       lokasi=i-1;
        if ((i - 1) >= 0&& i!=5&& i!=10 && i !=15) {//cek kiri kosong ga
            int a = i - 1;
            if (status[a] == 0) {
//                System.out.println("cekI bagian1");
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                bandinginfek=caloninfeksi;//dimasukin ke perbandinggan.. yang in tuh isian pertama
                lokasi=a;System.out.println("1"+a);// terus simpan lokasinya- lokasi ini tuh lokasinya a.. yaitu lokasi   calon anak beda lo sama lokasi infeksi
                //lokasi infeksi ga perlu di inget
            }
        }
        if ((i +1) <= 19&& i!=4 && i!=9 && i !=14) {//cek kanannya kosong enggak?
            int a = i + 1;
            if (status[a] == 0) {
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                if( caloninfeksi>bandinginfek){//ayo dilihat dulu sama yang sebelumnya besaran mana?
                    bandinginfek=caloninfeksi;// kalo besar ambil aja yang besar
                     lokasi=a;System.out.println("2"+a);// terus simpan lokasinya
                }
            }
        }
        if ((i + 5) <= 19&& i!=15 && i!=16 && i !=17 && i!=18) {//cek bawahnya kosong ennga?
            int a = i + 5;
            if (status[a] == 0) {
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                if( caloninfeksi>bandinginfek){//ayo dilihat dulu sama yang sebelumnya besaran mana?
                    bandinginfek=caloninfeksi;// kalo besar ambil aja yang besar
                     lokasi=a;System.out.println("3"+a);// terus simpan lokasinya
                }
            }
        }
        if ((i - 5) >= 0&& i!=1 && i!=2 && i !=3 && i!=4 ) {//cek atasnya kosog engga?
            int a = i - 5;
            if (status[a] == 0) {
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                if( caloninfeksi>bandinginfek){//ayo dilihat dulu sama yang sebelumnya besaran mana?
                    bandinginfek=caloninfeksi;// kalo besar ambil aja yang besar
                     lokasi=a;System.out.println("lokasi-");// terus simpan lokasinya
                    System.out.println("lokasi "+a);}
            }
        }
            if ((i + 4) <= 19) {//cek bawahnya kosong ennga?
            int a = i + 4;
            if (status[a] == 0) {
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                if( caloninfeksi>bandinginfek){//ayo dilihat dulu sama yang sebelumnya besaran mana?
                    bandinginfek=caloninfeksi;// kalo besar ambil aja yang besar
                     lokasi=a;System.out.println("3"+a);// terus simpan lokasinya
                }
            }
        }
        if ((i - 4) >= 0) {//cek atas kanannya kosog engga?
            int a = i - 4;
            if (status[a] == 0) {
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                if( caloninfeksi>bandinginfek){//ayo dilihat dulu sama yang sebelumnya besaran mana?
                    bandinginfek=caloninfeksi;// kalo besar ambil aja yang besar
                     lokasi=a;System.out.println("lokasi-");// terus simpan lokasinya
                    System.out.println("lokasi "+a);}
            }
        }
            if ((i + 6) <= 19) {//cek bawahnya kosong ennga?
            int a = i + 6;
            if (status[a] == 0) {
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                if( caloninfeksi>bandinginfek){//ayo dilihat dulu sama yang sebelumnya besaran mana?
                    bandinginfek=caloninfeksi;// kalo besar ambil aja yang besar
                     lokasi=a;System.out.println("3"+a);// terus simpan lokasinya
                }
            }
        }
        if ((i - 6) >= 0) {//cek atasnya kosog engga?
            int a = i - 6;
            if (status[a] == 0) {
                cekII(a);// jangan ditinggal ke sini dulu.. liat calon sekitar
                if( caloninfeksi>bandinginfek){//ayo dilihat dulu sama yang sebelumnya besaran mana?
                    bandinginfek=caloninfeksi;// kalo besar ambil aja yang besar
                     lokasi=a;System.out.println("lokasi-");// terus simpan lokasinya
                    System.out.println("lokasi "+a);}
            }
        }System.out.println("lokasi "+lokasi);
        //oke lokasinya fix terus gimana?jalanin infeksinya dong ><)/"
cek1[i]=lokasi;  
infeksicek1[i]=bandinginfek;
// infeksi(lokasi);
        System.out.println("print cekI"+lokasi);
        
    }

    void cekII(int i) {// liat sekitarnya kosong ada caloninfeksi engga?
        int k=0;
        caloninfeksi = 0;// di nolkan dulu biar nanti ga kemasukan lain2
        if ((i + 1) <= 19) {//cek kanannya infeksinya ad?
            k = i + 1;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
        if ((i - 1) >= 0) {//cek kirinya kosong enggak?infeksinya ad?
           k = i - 1;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
        if ((i + 5) <= 19) {//cek bawahnya infeksinya ad?
            k = i + 5;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
        if ((i - 5) >= 0) {//cek atasnya infeksinya ad?
            k = i - 5;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
            if ((i + 4) <= 19) {//cek bawahnya infeksinya ad?
            k = i + 4;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
        if ((i - 4) >= 0) {//cek atasnya infeksinya ad?
            k = i - 4;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
            if ((i + 6) <= 19) {//cek bawahnya infeksinya ad?
            k = i + 6;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
        if ((i - 6) >= 0) {//cek atasnya infeksinya ad?
            k = i - 6;
            if (status[k] == 1) {//ini jamur buat diinfeksi kan?
                caloninfeksi++;//ditambahin ke caloninfeksi deh
            }
        }
        System.out.println("nilai calon infeksi ="+caloninfeksi);
    }

    void infeksi(int i) {
     
        ubahjadiapel(i);System.out.println(" ubah apel" +i);
if ((i + 1) <= 1&&(i+1)!=4&&(i+1)!=9&&(i+1)!=14) {//cek kanannya ada ga? ntar eror lo
    
            int a = i + 1;
            if (status[a] == 1) {//sasarannnya hidup  ga? 
                ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        if ((i - 1) >= 0&&(i-1)!=5&&(i-1)!=10&&(i-1)!=15) {//cek kirinya kada ga? ntar eror lo
            int  a = i - 1;
            if (status[a] == 1) {//ini jamur buat diinfeksi kan?
                 ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        if ((i + 5) <= 19&&(i+5)!=15&&(i+5)!=16&&(i+5)!=17&&(i+5)!=18) {//cek bawahnya ada ga? ntar eror lo
            int a = i + 5;
            if (status[a] == 1) {//ini jamur buat diinfeksi kan?
                ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        if ((i - 5) >= 0) {//cek atasnya ada ga? ntar eror lo
             int a = i - 5;
            if (status[a] == 1) {//ini jamur buat diinfeksi kan?
                 ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        if ((i + 6) <= 19) {//cek kanannya ada ga? ntar eror lo
    
            int a = i + 6;
            if (status[a] == 1) {//sasarannnya hidup  ga? 
                ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        if ((i - 6) >= 0) {//cek kirinya kada ga? ntar eror lo
            int  a = i - 6;
            if (status[a] == 1) {//ini jamur buat diinfeksi kan?
                 ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        if ((i + 4) <= 19) {//cek bawahnya ada ga? ntar eror lo
            int a = i + 4;
            if (status[a] == 1) {//ini jamur buat diinfeksi kan?
                ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        if ((i - 4) >= 0) {//cek atasnya ada ga? ntar eror lo
             int a = i - 4;
            if (status[a] == 1) {//ini jamur buat diinfeksi kan?
                 ubahjadiapel(a);//ubah dia jadi apel hohoho
            }
        }
        System.out.println("infeksijalan niali a ="+i);
    }
//
    void ubahjadiapel(int a){
         switch (a) {
            case 0:
                status[0] = 2;
                B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
            case 1:
                status[1] = 2;
                B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 2:
                status[2] = 2;
                B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 3:
                status[3] = 2;
                B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 4:
                status[4] = 2;
                B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 5:
                status[5] = 2;
                B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 6:
                status[6] = 2;
                B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 7:
                status[7] = 2;
                B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 8:
                status[8] = 2;
                B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
           case 9:
                status[9] = 2;
                B10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 10:
                status[10] = 2;
                B11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 11:
                status[11] = 2;
                B12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 12:
                status[12] = 2;
                B13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 13:
                status[13] = 2;
                B14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 15:
                status[15] = 2;
                B16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 16:
                status[16] = 2;
                B17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 17:
                status[17] = 2;
                B18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 18:
                status[18] = 2;
                B19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            case 19:
                status[19] = 2;
                B20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/apple2.png")));
                break;
            default:
                System.out.println("eror");

        }
        
    }
//

    void jadikanjamur(int s) {
        switch (s) {
            case 0:
                status[0] = 1;
                B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
            case 1:
                status[1] = 1;
                B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 2:
                status[2] = 1;
                B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 3:
                status[3] = 1;
                B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 4:
                status[4] = 1;
                B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 5:
                status[5] = 1;
                B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 6:
                status[6] = 1;
                B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 7:
                status[7] = 1;
                B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 8:
                status[8] = 1;
                B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 9:
                status[9] = 1;
                B10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 10:
                status[10] = 1;
                B11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 11:
                status[11] = 1;
                B12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 12:
                status[12] = 1;
                B13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 13:
                status[13] = 1;
                B14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 15:
                status[15] = 1;
                B16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 16:
                status[16] = 1;
                B17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 17:
                status[17] = 1;
                B18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 18:
                status[18] = 1;
                B19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            case 19:
                status[19] = 1;
                B20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/mushroom.png")));
                break;
            default:
                System.out.println("eror");

        }

    }
//

    void ubahapel(int state) {
        int k;
//mengubah musuh-apel
          if ((state - 4) >= 0) {  //atas
            k = (state - 4);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }
        if ((state + 4) <=19) {  //bawah
            k = (state + 4);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }
        if ((state - 6) >= 0) {  //kiri
            k = (state - 6);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }
        if ((state + 6) <= 19) {  //kanan
            k = (state + 6);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }

        if ((state - 5) >= 0) {  //atas
            k = (state - 5);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }
        if ((state + 5) <=19) {  //bawah
            k = (state + 5);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }
        if ((state - 1) >= 0) {  //kiri
            k = (state - 1);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }
        if ((state + 1) <= 19) {  //kanan
            k = (state + 1);
            if (status[k] == 2) {
                jadikanjamur(k);
            }
        }

    }
    
    void cekpenuh() {
        int tunggal = 0;
        int tunggal2=0;
        int tunggallokasi = 0;
        if (status[0] != 0 && status[1] != 0 && status[2] != 0 && status[3] != 0 && status[4] != 0 && status[5] != 0 && status[6] != 0 && status[7] != 0 && status[8] != 0 && status[9] != 0&&status[10] != 0 && status[11] != 0 && status[12] != 0 && status[13] != 0 && status[14] != 0 && status[15] != 0 && status[16] != 0 && status[17] != 0 && status[18] != 0) {
            cekskor();
        }
        for (int i = 0; i < 19; i++) {
            
            
            if (status[i] == 1) {
                tunggal++;
                tunggallokasi = i;
                System.out.println("tunggallokasi= "+tunggal);
               tunggal2=tunggal2+ cektunggal(tunggallokasi);
            }
        }
       if(tunggal==1){
           cektunggal(tunggallokasi);
       }
       if (tunggal==0){
            JOptionPane.showMessageDialog(rootPane, "Anda kalah");
       }
       
       if(tunggal2==0){
           JOptionPane.showMessageDialog(rootPane, "Anda kalah");
       }
        
    }
    
    int cektunggal(int i){
        int kosong = 0;
      if ((i + 1) <= 8 && i != 2 && i != 5&& status[i+1]==0) {//cek kanannya ada ga? ntar liat bisa jalan atas bawah atau enggak
kosong ++;
        }
        if ((i - 1) >= 0 && i!=4 && i!=9 && i!=14 && i!=19 && status[i-1]==0) {//cek kirinya kada ga? ntar liat bisa jalan atas bawah atau enggak
          kosong ++;
        }
        
        if ((i + 5) >= 0&& i != 15 && i != 16 && i!=17&& i != 18 && i!=19 && status[i+5]==0) {//cek kiriatas? ntar eror lo ntar liat bisa jalan atas bawah atau enggak
          kosong ++;
        }    if ((i - 5) >= 0&& i != 0 && i != 1 && i!=2 && i!= 3 && i!=4 && status[i-5]==0) {//cek atasnya ada ga? ntar eror lo ntar liat bisa jalan atas bawah atau enggak
          kosong ++;
        }
        if ((i - 4) >= 0 && i!=0 && i!= 1 && i!=2  && i!=3 && i!=4  && i!=9 && i!=14 && i!=19 && status[i-4]==0) {//cek kananatas? ntar eror lo ntar liat bisa jalan atas bawah atau enggak
          kosong ++;
        } 
        if ((i +4) >= 0 && i!=0 && i!= 5 && i!=10  && i!=15 && i!=16  && i!=17 && i!=18 && i!=19 && status[i+4]==0) {//cek kiribawah? ntar eror lo ntar liat bisa jalan atas bawah atau enggak
          kosong ++;
        } 
        if ((i +6) >= 0&& i != 14 && i!=4  &&i != 9&& i != 15 && i!=16  &&i != 17&& i != 18 && i!=19 && status[i+6]==0) {//cek kanan bawah? ntar eror lo ntar liat bisa jalan atas bawah atau enggak
          kosong ++;
        } 
        if ((i -6) >= 0&& i!=0 && i!=1  && i!=2 && i!=3 && i!=4  && i!=10 && i!= 15 && i!=5 && status[i-6]==0) {//cek kanan bawah? ntar eror lo ntar liat bisa jalan atas bawah atau enggak
          kosong ++;
        }
   return kosong;
    }
      void cekskor() {
        int apels = 0 ;
        int jamurs = 0 ;
        int pr = 0;
        for (int i = 0; i < 19; i++) {
            
            if (status[i] == 1) {
                jamurs =jamurs+10;
                pr++;
            }
            if (status[i] == 2) {
                apels =apels+10;//cekada(i);
                pr++;
            }
            
        } 
        nilai(jamurs,apels);
      

    }


   
   void nilai(int jamurs,int apels){
                 if (jamurs < apels) {
                    JOptionPane.showMessageDialog(rootPane, "Anda kalah");
                new namaH(jamurs).setVisible(true);
                }  if (jamurs > apels) {
                    JOptionPane.showMessageDialog(rootPane, "Anda menang");
                    new namaH(jamurs).setVisible(true);
                }
    }
//}
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jalanhard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jalanhard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jalanhard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jalanhard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jalanhard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B11;
    private javax.swing.JButton B12;
    private javax.swing.JButton B13;
    private javax.swing.JButton B14;
    private javax.swing.JButton B15;
    private javax.swing.JButton B16;
    private javax.swing.JButton B17;
    private javax.swing.JButton B18;
    private javax.swing.JButton B19;
    private javax.swing.JButton B2;
    private javax.swing.JButton B20;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton gochan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel jumlahjamur;
    // End of variables declaration//GEN-END:variables
}
