/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mushroomattack;

import java.awt.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Yopie
 */
public class score extends javax.swing.JFrame {

    /**
     * Creates new form score
     */
    public score() throws SQLException {
        initComponents();
        List nama = new List();
        List skor = new List();
        
        try{
           Connection c = koneksi.getkoneksi();
           Statement s = c.createStatement();
           
           String sql = "SELECT * from skor "
                   + "ORDER BY skor desc";
           
            ResultSet res = s.executeQuery(sql);
            while(res.next()){
                nama.add(res.getString("nama"));
                skor.add(res.getString("skor"));
            }
        }
            catch(SQLException ex){
            System.out.println(ex);
        }
        
        nama1.setText(nama.getItem(0));
        nama2.setText(nama.getItem(1));
        nama3.setText(nama.getItem(2));
        skor1.setText(skor.getItem(0));
        skor2.setText(skor.getItem(1));
        skor3.setText(skor.getItem(2));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama3 = new javax.swing.JLabel();
        skor2 = new javax.swing.JLabel();
        nama1 = new javax.swing.JLabel();
        skor3 = new javax.swing.JLabel();
        skor1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(jLabel2.getPreferredSize());
        setPreferredSize(new java.awt.Dimension(953, 681));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("High Score");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 170, 190, 46);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel3.setText("2.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 340, 50, 40);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel4.setText("3.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 410, 50, 40);

        nama2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        nama2.setText("Z");
        getContentPane().add(nama2);
        nama2.setBounds(310, 340, 250, 40);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel6.setText("1.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 280, 50, 40);

        nama3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        nama3.setText("Z");
        getContentPane().add(nama3);
        nama3.setBounds(310, 410, 250, 40);

        skor2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        skor2.setText("10");
        getContentPane().add(skor2);
        skor2.setBounds(610, 340, 60, 40);

        nama1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        nama1.setText("Z");
        getContentPane().add(nama1);
        nama1.setBounds(310, 280, 250, 40);

        skor3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        skor3.setText("10");
        getContentPane().add(skor3);
        skor3.setBounds(610, 410, 60, 40);

        skor1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        skor1.setText("10");
        getContentPane().add(skor1);
        skor1.setBounds(610, 280, 60, 40);

        jButton1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 500, 110, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomattack/bg2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 634);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new awal().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new score().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(score.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nama2;
    private javax.swing.JLabel nama3;
    private javax.swing.JLabel skor1;
    private javax.swing.JLabel skor2;
    private javax.swing.JLabel skor3;
    // End of variables declaration//GEN-END:variables


}
